export const BD_DIVISIONS = [
  "Barishal",
  "Chittagong",
  "Dhaka",
  "Khulna",
  "Mymensingh",
  "Rajshahi",
  "Rangpur",
  "Sylhet",
];

export const DISTRICTS_BY_DIVISION = {
  Barishal: [
    "Barguna",
    "Barishal",
    "Bhola",
    "Jhalokati",
    "Patuakhali",
    "Pirojpur",
  ],
  Chittagong: [
    "Bandarban",
    "Brahmanbaria",
    "Chandpur",
    "Chattogram",
    "Cumilla",
    "Cox's Bazar",
    "Feni",
    "Khagrachhari",
    "Lakshmipur",
    "Noakhali",
    "Rangamati",
  ],
  Dhaka: [
    "Dhaka",
    "Faridpur",
    "Gazipur",
    "Gopalganj",
    "Kishoreganj",
    "Madaripur",
    "Manikganj",
    "Munshiganj",
    "Narayanganj",
    "Narsingdi",
    "Rajbari",
    "Shariatpur",
    "Tangail",
  ],
  Khulna: [
    "Bagerhat",
    "Chuadanga",
    "Jashore",
    "Jhenaidah",
    "Khulna",
    "Kushtia",
    "Magura",
    "Meherpur",
    "Narail",
    "Satkhira",
  ],
  Mymensingh: ["Jamalpur", "Mymensingh", "Netrokona", "Sherpur"],
  Rajshahi: [
    "Bogura",
    "Joypurhat",
    "Naogaon",
    "Natore",
    "Chapainawabganj",
    "Pabna",
    "Rajshahi",
    "Sirajganj",
  ],
  Rangpur: [
    "Dinajpur",
    "Gaibandha",
    "Kurigram",
    "Lalmonirhat",
    "Nilphamari",
    "Panchagarh",
    "Rangpur",
    "Thakurgaon",
  ],
  Sylhet: ["Habiganj", "Moulvibazar", "Sunamganj", "Sylhet"],
};

const fallbackLocationTree = Object.fromEntries(
  Object.entries(DISTRICTS_BY_DIVISION).map(([divisionName, districts]) => [
    divisionName,
    Object.fromEntries(
      districts.map((districtName) => [
        districtName,
        [`${districtName} Sadar`],
      ]),
    ),
  ]),
);

export const LOCATION_TREE = {
  ...fallbackLocationTree,
  Dhaka: {
    ...fallbackLocationTree.Dhaka,
    Dhaka: [
      "Dhanmondi",
      "Gulshan",
      "Mirpur",
      "Uttara",
      "Mohammadpur",
      "Keraniganj",
      "Savar",
    ],
    Gazipur: ["Gazipur Sadar", "Kaliakair", "Sreepur", "Kapasia"],
    Narayanganj: ["Narayanganj Sadar", "Fatullah", "Sonargaon", "Rupganj"],
    Narsingdi: ["Narsingdi Sadar", "Belabo", "Monohardi", "Raipura"],
    Tangail: ["Tangail Sadar", "Madhupur", "Ghatail"],
  },
  Chittagong: {
    ...fallbackLocationTree.Chittagong,
    Chattogram: ["Kotwali", "Pahartali", "Panchlaish", "Patenga", "Sitakunda"],
    "Cox's Bazar": ["Cox's Bazar Sadar", "Ramu", "Teknaf", "Ukhia"],
    Cumilla: ["Cumilla Sadar", "Daudkandi", "Burichang", "Laksam"],
  },
  Khulna: {
    ...fallbackLocationTree.Khulna,
    Khulna: ["Khalishpur", "Sonadanga", "Dumuria", "Batiaghata"],
    Jashore: ["Jashore Sadar", "Bagherpara", "Chowgacha", "Monirampur"],
    Satkhira: ["Satkhira Sadar", "Kaliganj", "Assasuni", "Shyamnagar"],
  },
  Rajshahi: {
    ...fallbackLocationTree.Rajshahi,
    Rajshahi: ["Boalia", "Motihar", "Paba", "Bagha"],
    Bogura: ["Bogura Sadar", "Sherpur", "Shibganj", "Dupchanchia"],
    Pabna: ["Pabna Sadar", "Ishwardi", "Sujanagar", "Bera"],
  },
  Sylhet: {
    ...fallbackLocationTree.Sylhet,
    Sylhet: ["Kotwali", "Beanibazar", "Balaganj", "Golapganj"],
    Moulvibazar: ["Moulvibazar Sadar", "Sreemangal", "Kulaura", "Rajnagar"],
    Habiganj: ["Habiganj Sadar", "Madhabpur", "Nabiganj", "Chunarughat"],
  },
  Barishal: {
    ...fallbackLocationTree.Barishal,
    Barishal: ["Kotwali", "Bakerganj", "Babuganj", "Uzirpur"],
    Bhola: ["Bhola Sadar", "Borhanuddin", "Lalmohan", "Char Fasson"],
    Patuakhali: ["Patuakhali Sadar", "Kalapara", "Mirzaganj", "Dashmina"],
  },
  Mymensingh: {
    ...fallbackLocationTree.Mymensingh,
    Mymensingh: ["Mymensingh Sadar", "Trishal", "Bhaluka", "Gafargaon"],
    Jamalpur: ["Jamalpur Sadar", "Melandaha", "Sarishabari", "Islampur"],
    Netrokona: ["Netrokona Sadar", "Purbadhala", "Madan", "Kendua"],
  },
  Rangpur: {
    ...fallbackLocationTree.Rangpur,
    Rangpur: ["Rangpur Sadar", "Mithapukur", "Pirgachha", "Badarganj"],
    Dinajpur: ["Dinajpur Sadar", "Birampur", "Parbatipur", "Birganj"],
    Kurigram: ["Kurigram Sadar", "Nageshwari", "Ulipur", "Rajarhat"],
  },
};
