const HOME_FEATURED_PROPERTIES = [
  {
    id: 1,
    category: "Family",
    title: "Premium Family Flat",
    location: "Dhanmondi",
    division: "Dhaka",
    price: "25,000",
    beds: 3,
    baths: 3,
    sqft: 1500,
    image: "/2 Bedroom.png",
  },
  {
    id: 2,
    category: "Family",
    title: "Standard Family Apartment",
    location: "Mirpur 10",
    division: "Dhaka",
    price: "18,000",
    beds: 2,
    baths: 2,
    sqft: 1100,
    image: "/3baderoom.png",
  },
  {
    id: 3,
    category: "Family",
    title: "Affordable Family House",
    location: "Uttara",
    division: "Dhaka",
    price: "20,000",
    beds: 3,
    baths: 2,
    sqft: 1200,
    image: "/2 Bedroom.png",
  },
  {
    id: 4,
    category: "Bachelor",
    title: "Single Bachelor Room",
    location: "Mohammadpur",
    division: "Dhaka",
    price: "6,000",
    beds: 1,
    baths: 1,
    sqft: 300,
    image: "/SingleRoom.png",
  },
  {
    id: 5,
    category: "Bachelor",
    title: "Shared Bachelor Mess",
    location: "Farmgate",
    division: "Dhaka",
    price: "4,000",
    beds: 1,
    baths: 1,
    sqft: 500,
    image: "/Bacelor.png",
  },
  {
    id: 6,
    category: "Bachelor",
    title: "Executive Bachelor Flat",
    location: "Gulshan",
    division: "Dhaka",
    price: "15,000",
    beds: 1,
    baths: 1,
    sqft: 600,
    image: "/SingleRoom.png",
  },
  {
    id: 7,
    category: "Office",
    title: "Corporate Office Space",
    location: "Banani",
    division: "Dhaka",
    price: "80,000",
    beds: null,
    baths: 2,
    sqft: 2000,
    image: "/Master.png",
  },
  {
    id: 8,
    category: "Office",
    title: "Small Startup Office",
    location: "Badda",
    division: "Dhaka",
    price: "30,000",
    beds: null,
    baths: 1,
    sqft: 800,
    image: "Office Floor Rent.png",
  },
  {
    id: 9,
    category: "Office",
    title: "Co-working Space Desk",
    location: "Karwan Bazar",
    division: "Dhaka",
    price: "10,000",
    beds: null,
    baths: 1,
    sqft: 150,
    image:
      "https://dreamtouch-bd.com/wp-content/uploads/elementor/thumbs/small-duplex-house-design-in-bangladesh-%E2%80%93-modern-exterior-view-r1roygzxrj534v2p6nclwjnnucaof522he3574p1hk.webp",
  },
  {
    id: 20,
    category: "Office",
    title: "Office Floor Rent",
    location: "Uttara 10",
    division: "Dhaka",
    price: "15,000",
    beds: null,
    baths: 1,
    sqft: 150,
    image:
      "https://dreamtouch-bd.com/wp-content/uploads/elementor/thumbs/small-duplex-house-design-in-bangladesh-%E2%80%93-modern-exterior-view-r1roygzxrj534v2p6nclwjnnucaof522he3574p1hk.webp",
  },
  {
    id: 10,
    category: "Sublet",
    title: "Sublet for Female",
    location: "Azimpur",
    division: "Dhaka",
    price: "5,500",
    beds: 1,
    baths: 1,
    sqft: 250,
    image: "/SingleRoom.png",
  },
  {
    id: 11,
    category: "Sublet",
    title: "Master Bed Sublet",
    location: "Bashundhara R/A",
    division: "Dhaka",
    price: "8,000",
    beds: 1,
    baths: 1,
    sqft: 400,
    image: "/Master.png",
  },
  {
    id: 12,
    category: "Sublet",
    title: "Single Room Sublet",
    location: "Khilgaon",
    division: "Dhaka",
    price: "6,000",
    beds: 1,
    baths: 1,
    sqft: 300,
    image: "/Bacelor.png",
  },
  {
    id: 13,
    category: "Hostel",
    title: "Boys Premium Hostel",
    location: "Panthapath",
    division: "Dhaka",
    price: "5,000",
    beds: 1,
    baths: 1,
    sqft: 200,
    image: "/SingleRoom.png",
  },
  {
    id: 14,
    category: "Hostel",
    title: "Girls Safe Hostel",
    location: "Shantinagar",
    division: "Dhaka",
    price: "6,500",
    beds: 1,
    baths: 1,
    sqft: 250,
    image: "/Bacelor.png",
  },
  {
    id: 15,
    category: "Hostel",
    title: "Executive Working Hostel",
    location: "Tejgaon",
    division: "Dhaka",
    price: "7,000",
    beds: 1,
    baths: 1,
    sqft: 220,
    image: "/SingleRoom.png",
  },
];

const BROWSE_PROPERTIES = [
  {
    id: 1,
    title: "2 Bedroom Apartment",
    location: "Dhanmondi, Dhaka",
    division: "Dhaka",
    beds: 2,
    type: "Apartment",
    price: "15,000",
    image:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 2,
    title: "Bachelor Room",
    location: "Mohammadpur, Dhaka",
    division: "Dhaka",
    beds: 1,
    type: "Room",
    price: "6,000",
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1f51baffac3?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 3,
    title: "3 Bedroom Family House",
    location: "Gulshan, Dhaka",
    division: "Dhaka",
    beds: 3,
    type: "House",
    price: "35,000",
    image:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 4,
    title: "Commercial Shop",
    location: "Mirpur, Dhaka",
    division: "Dhaka",
    beds: 0,
    type: "Shop",
    price: "25,000",
    image:
      "https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 5,
    title: "Studio Apartment",
    location: "Banani, Dhaka",
    division: "Dhaka",
    beds: 1,
    type: "Apartment",
    price: "12,000",
    image:
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 6,
    title: "4 Bedroom Duplex",
    location: "Uttara, Dhaka",
    division: "Dhaka",
    beds: 4,
    type: "House",
    price: "45,000",
    image:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
  },
];

const KNOWN_PROPERTY_CATALOG = [
  ...HOME_FEATURED_PROPERTIES,
  ...BROWSE_PROPERTIES,
].reduce((catalog, property) => {
  catalog.set(String(property.id), property);
  return catalog;
}, new Map());

const getCatalogPropertyById = (propertyId) =>
  KNOWN_PROPERTY_CATALOG.get(String(propertyId));

export { BROWSE_PROPERTIES, getCatalogPropertyById, HOME_FEATURED_PROPERTIES };
